### ISSUE TITLE
roadmapping

### ISSUE THREAD

**Issue by serapath** [playproject-io/datdot-vault#1]
## `@todo`
* [ ] [`datdot-research#6` user accounts + (API & UI)](https://github.com/playproject-io/datdot-research/issues/6)
* [ ] [`datdot-vault#2` ux/design ideas](https://github.com/playproject-io/datdot-vault/issues/2)
* [ ] decide on localhost domain (see https://tools.ietf.org/id/draft-chapin-rfc2606bis-00.html), e.g.:
    * `https://datdot.local`
    * `https://datdot.home`
    * `https://datdot.host`
    * `https://datdot.localhost`
    * `https://datdot.lan`
* [ ] use `mkcert` to cross-platform generate a CA certificate and add it to the main browser
* [ ] run minimal local secure web server with support for secure websockets
* [ ] daemonify the server and run it on startup
* [ ] implement vault website to mange the vault on a localhost domain
* [ ] implement the vault to create an account for a an app like `datdot` via iframe

---
